baseURL = "https://wakan.github.io"
defaultContentLanguage = "fr"  # For HTML page, now support: en, zh-hans, zh-hant, ja, nl, pl, it
enableGitInfo = true
languageCode = "fr-FR"  # For RSS, view https://www.rssboard.org/rss-language-codes
noChmod = true
noTimes = true
summaryLength = 200 # Custom summary length, add <!--more--> in post file to custom split point
timezone = "Europe/Paris"
title = "WaKaN's blog"
theme = "terminal"

[ouputs]
  home = ["HTML", "RSS", "AMP"]

[pagination]
pagerSize = 21
