  [goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Enable user to embed HTML snippets in Markdown content
  [highlight]
    codeFences = false  # Disable Hugo's code highlighter

  [tableOfContents]
    startLevel = 2
    endLevel = 3
