  [[nav]]
    name = "Home"
    url = "/"
    weight = 1
  [[nav]]
    name = "RSS"
    url = "/index.xml"
    weight = 5

  [[link]]
    name = "GitHub"
    url = "https://github.com/wakan"
    weight = 1
