  [[menus.main]]
    name = "Home"
    pageRef = "/"
    weight = 10
  [[menus.main]]
    name = "RSS"
    pageRef = "/index.xml"
    weight = 50

  [[menus.main]]
    name = "GitHub"
    url = "https://github.com/wakan"
    weight = 10
    [menus.main.params]
      rel = 'external'
