  author = "wakan" # You can also set author in post front matter individually
  profilePicture = "/img/wakan.jpg"

  # Source URL of the website, will appear in the footer
  sourceURL = "https://github.com/wakan/blog"

  # Word counter and read time indicator in post metadata
  showWordCounter = true
  showReadTime = true

  showToc = true

  copyrightStartYear = "2016"

  description = "Un mix de glandouille, informatique, drone, iles et surtout des tests divers"
  og = "/img/wakan.jpg"

  # Posts shown in homepage
  mainSections = ["post"]

  # License
  license = "CC BY-NC-SA 4.0"
  licenseLink = "http://creativecommons.org/licenses/by-nc-sa/4.0/"

  disqusShortname = "wakanpowa"
