baseurl = "https://wakan.github.io/blog/"
languageCode = "fr-FR"
title = "WaKaN's blog"
enableGitInfo = true
theme = "hyde-hyde"
copyright = "&copy; 2018 Guillaume Laurent"
GoogleAnalytics = "UA-104313067-1"
# Enable comments by entering your Disqus shortname
DisqusShortname = "wakanpowa"


[taxonomies]
tag = "tags"
category = "categories"
series = "series"


 date_format = "Mon 2 Jan 2006"

 math = false

sharing = true

[[menu.main]]
  name = "Posts"
  url = "#posts"
  weight = 3

[[menu.main]]
  name = "Contact"
  url = "#contact"
weight = 5


[outputs]
page = [ "HTML", "AMP" ] # if you want AMP enable.



