#baseurl = "https://wakan.github.io/blog/"
baseurl = "https://ipfs.io/ipns/Qmaf2Dqi17apQHrCBjFaVCn6qRjG1EN8wdDW12HqQsqLUW/"
languageCode = "fr-FR"
title = "WaKaN's blog"
theme = "hugo_theme_robust"
copyright = "&copy; 2018 Guillaume Laurent"
GoogleAnalytics = "UA-104313067-1"
# Enable comments by entering your Disqus shortname
DisqusShortname = "wakanpowa"
canonifyURLs=false
  

[permalinks]
  post = "/:title/"

[taxonomies]
tag = "tags"
category = "categories"
series = "series"


[params]
  description = "Un mix de glandouille, informatique, drone et Iles"
  dateformat = "Jan 2, 2006" # Optional
 date_format = "Mon 2 Jan 2006"

[params.author]
  thumbnail = "img/wakan.jpg"
  name = "WaKaN PoWa"
  description = "Microsoft fan. Pour un web meilleur."
  facebook = "//facebook.com/wakan"
  twitter = "//twitter.com/wakanpowa"
  github = "//github.com/wakan"

[outputs]
page = [ "HTML", "AMP" ] # if you want AMP enable.
