baseurl = "https://wakan.github.io/blog/"
languageCode = "fr-FR"
title = "WaKaN's blog"
theme = "hugo_theme_robust"
copyright = "&copy; 2018 Guillaume Laurent"
GoogleAnalytics = "UA-104313067-1"
# Enable comments by entering your Disqus shortname
DisqusShortname = "wakanpowa"
canonifyURLs=false
uglyurls=true
relativeURLs=true

[permalinks]
  post = "/:title/"

[taxonomies]
tag = "tags"
category = "categories"
series = "series"


[params]
  description = "Un mix de glandouille, informatique, drone et Iles"
  dateformat = "Jan 2, 2006" # Optional
  # Fonts settings.
  googlefonts = "https://fonts.googleapis.com/css?family=Lobster|Lato:400,700" # Optional, Include google fonts.
  fontfamily = "Lato,YuGothic,'Hiragino Kaku Gothic Pro',Meiryo,sans-serif" # Optional, Override body font family.
  logofontfamily = "Lobster, cursive" # Optional, Override logo font.
 date_format = "Mon 2 Jan 2006"

[params.author]
  thumbnail = "img/wakan.jpg"
  name = "WaKaN PoWa"
  description = "Microsoft fan"
  facebook = "//facebook.com/wakan"
  twitter = "//twitter.com/wakanpowa"
  github = "//github.com/wakan"

[outputs]
page = [ "HTML", "AMP" ] # if you want AMP enable.
