DisqusShortname = "wakanpowa"
GoogleAnalytics = "UA-104313067-1"
copyright = "&copy; 2021 Guillaume Laurent"
languageCode = "fr-FR"
theme = "ananke"
title = "WaKaN's blog"
[outputs]
page = ["HTML", "AMP"]
[params]
date_format = "Mon 2 Jan 2006"
dateformat = "Jan 2, 2006"
description = "Un mix de glandouille, informatique, drone, iles et sutour des tests divers"
[params.author]
description = "Microsoft fan. Pour un web meilleur."
facebook = "//facebook.com/wakan"
github = "//github.com/wakan"
name = "WaKaN PoWa"
thumbnail = "img/wakan.jpg"
twitter = "//twitter.com/wakanpowa"
[permalinks]
post = "/:title/"
[taxonomies]
category = "categories"
series = "series"
tag = "tags"
